version: '2'
services:

  nginx:
    build: ./nginx
    depends_on:
      - api
      - admin
    ports:
      - "8080:8080"
      - "8081:8081"

  api:
    build: ./api
    ports:
      - "8080"
    depends_on:
      - db

  admin:
    build: ./admin
    ports:
      - "8080"
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5432"
